#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(i32)]
pub enum Op {
    Ctor = 0,
    Dtor = 1,
    Copy = 2,
    Get = 3,
    Set = 4,
    IsErr = 5,
    Name = 6,
    Add = 7,
    Sub = 8,
    Mul = 9,
    Div = 10,
    Modd = 11,
    Radd = 12,
    Rsub = 13,
    Rmul = 14,
    Rdiv = 15,
    Rmodd = 16,
    LogNot = 17,
    Shl = 18,
    Shr = 19,
    BitAnd = 20,
    BitOr = 21,
    BitNot = 22,
    Cmp = 23,
    Len = 24,
    Iter = 25,
}